const examplesarray = [
    ["Lazy", "Kind of Blue", "Miles Davis", 60],
    ["Lazy", "Hotel California", "Eagles", 75],
    ["Lazy", "Superunknown", "Soundgarden", 70],
    ["Lazy", "The Chronic", "Dr. Dre", 80],
    ["Lazy", "Pet Sounds", "The Beach Boys", 75],
    ["Lazy", "L.A. Woman", "The Doors", 90],
    ["Reflective", "Rumours", "Fleetwood Mac", 90],
    ["Reflective", "OK Computer", "Radiohead", 110],
    ["Reflective", "What's Going On", "Marvin Gaye", 85],
    ["Reflective", "The Stranger", "Billy Joel", 90],
    ["Reflective", "Wish You Were Here", "Pink Floyd", 65],
    ["Reflective", "Blood on the Tracks", "Bob Dylan", 80],
    ["Reflective", "The Suburbs", "Arcade Fire", 100],
    ["Smooth", "Kind of Blue", "Miles Davis", 70],
    ["Groovy", "Off the Wall", "Michael Jackson", 120],
    ["Energized", "Thriller", "Michael Jackson", 120],
    ["Energized", "Back in Black", "AC/DC", 130],
    ["Energized", "Born to Run", "Bruce Springsteen", 130],
    ["Energized", "Raising Hell", "Run-D.M.C.", 130],
    ["Energized", "A Day at the Races", "Queen", 100],
    ["Energized", "Bad", "Michael Jackson", 110],
    ["Energized", "Off the Wall", "Michael Jackson", 100],
    ["Intense", "The Wall", "Pink Floyd", 140],
    ["Intense", "Ride the Lightning", "Metallica", 150],
    ["Intense", "Master of Puppets", "Metallica", 150],
    ["Epic", "Led Zeppelin IV", "Led Zeppelin", 110],
    ["Intense", "Dark Fantasy", "Kanye West", 120],
    ["Intense", "Sticky Fingers", "The Rolling Stones", 140],
    ["Intense", "In the Court of the Crimson King", "King Crimson", 110],
    ["Trippy", "Electric Ladyland", "Jimi Hendrix", 110],
    ["Mysterious", "Synchronicity", "The Police", 120],
    ["Hopeful", "The Joshua Tree", "U2", 95],
    ["Spiritual", "A Love Supreme", "John Coltrane", 80],
    ["Brooding", "Mezzanine", "Massive Attack", 90],
    ["Innovative", "Sgt. Pepper's Lonely Hearts Club Band", "The Beatles", 120],
    ["Dreamy", "Hunky Dory", "David Bowie", 95],
    ["Serene", "Bridge Over Troubled Water", "Simon & Garfunkel", 65],
    ["Rebellious", "The Queen Is Dead", "The Smiths", 120],
    ["Trippy", "Electric Ladyland", "Jimi Hendrix", 110],
    ["Mellow", "Kind of Blue", "Miles Davis", 60],
    ["Soulful", "Blue", "Joni Mitchell", 80],
    ["Sultry", "Back to Black", "Amy Winehouse", 100],
    ["Raw", "Nevermind", "Nirvana", 140],
    ["Gritty", "Exile on Main St.", "The Rolling Stones", 140],
    ["Relaxed", "Abbey Road", "The Beatles", 80],
    ["Laid-back", "Hotel California", "Eagles", 75],
    ["Jazzy", "Court and Spark", "Joni Mitchell", 90],
    ["Spacey", "The Rise and Fall of Ziggy Stardust", "David Bowie", 95],
    ["Dramatic", "A Night at the Opera", "Queen", 100],
    ["Funky", "Off the Wall", "Michael Jackson", 100]
]


module.exports = { examplesarray }